### ISSUE TITLE
The Goals is false

### ISSUE THREAD

**Issue by lubodrinka** [freeCodeCamp/boilerplate-project-exercisetracker#2]
https://fuschia-custard.glitch.me/
look at this model from freecodecamp and there is goal
GET users's exercise log: GET /api/exercise/log?{userId}[&from][&to][&limit]
{ } = required, [ ] = optional
from, to = dates (yyyy-mm-dd); limit = number
who had write that and think we all understand him as
https://fuschia-custard.glitch.me/api/exercise/log?userId=SyKsUMHNm&from=2014-01-08&to=2018-07-24&limit=5
that is really mean trick I was stuck for a day.
Please rewrite the goals to be more understandable.
https://forum.freecodecamp.org/t/excercise-tracker-get-userss-exercise-log/211435/15

**Comment by tmstani23** [comment]
Yea I agree the requirements are really vague and incorrect.  I tried putting in the route parameter and got an error unknown userId.  This is because the instructions are incorrect.  "GET /api/exercise/log?{userId}[&from][&to][&limit]", should be "GET /api/exercise/log?**=**{userId}[&from][&to][&limit]"

**Comment by crandalj** [comment]
I ran a test against mine and it passes everything when I don't even have the GET route doing anything other than passing a TODO object. Not sure if anyone is still monitoring the issue but it's definitely not correct.

**Comment by moT01** [comment]
Please open issues on the [main repo](https://github.com/freeCodeCamp/freeCodeCamp/issues) for these. Thanks and happy coding 🎉
